import { useEffect, useState } from 'react'
import PayrollHistoryTable from '../components/PayrollHistoryTable'
import SalaryComponentTable from '../components/SalaryComponentTable'
import SalarySummaryCard from '../components/SalarySummaryCard'
import { useAuth } from '../hooks/useAuth'
import { getEmployees } from '../services/employeeService'
import { generatePayroll, getEmployeePayroll, getMyPayroll, getSalary, updateSalary } from '../services/payrollService'

function Heading({ children, label, copy }) { return <div className="page-heading"><div><p className="eyebrow">{label}</p><h1>{children}</h1><p className="welcome-copy">{copy}</p></div><span className="employee-count">Payroll workspace</span></div> }
function asArray(value) { return Array.isArray(value) ? value : value?.records || value?.payroll || [] }
function SalaryView({ employee, admin }) {
  const [salary, setSalary] = useState(null); const [history, setHistory] = useState([]); const [editing, setEditing] = useState(false); const [notice, setNotice] = useState(''); const [error, setError] = useState('')
  useEffect(() => { if (!employee) return; const load = admin ? Promise.all([getSalary(employee.id || employee.employeeId), getEmployeePayroll(employee.id || employee.employeeId)]) : getMyPayroll().then((records) => { const latest = records[0]; return [latest ? { monthlyWage: latest.gross, yearlyWage: 'Available in salary profile', netSalary: latest.net } : null, records] }); load.then(([loadedSalary, loadedPayroll]) => { setSalary(loadedSalary); setHistory(asArray(loadedPayroll)) }).catch((loadError) => setError(loadError.message)) }, [employee, admin])
  if (!employee) return <p className="empty-state">Select an employee to view payroll.</p>
  if (!salary) return <p className="empty-state">{error || 'Loading salary and payroll...'}</p>
  const components = salary.components || [['Basic Salary', salary.basicSalary], ['HRA', salary.hra], ['Standard Allowance', salary.standardAllowance], ['Performance Bonus', salary.performanceBonus], ['Leave Travel Allowance', salary.leaveTravelAllowance], ['Fixed Allowance', salary.fixedAllowance]].filter((row) => row[1] != null)
  const deductions = salary.deductions || [['Provident Fund', salary.providentFund], ['Professional Tax', salary.professionalTax]].filter((row) => row[1] != null)
  async function saveSalary() { try { await updateSalary(employee.id || employee.employeeId, salary); setEditing(false); setNotice('Salary structure saved (mock UI state confirmed by API).') } catch (saveError) { setError(saveError.message) } }
  async function handleGenerate() { try { await generatePayroll({ employeeId: employee.id || employee.employeeId }); setNotice('Payroll generation completed.') } catch (generateError) { setError(generateError.message) } }
  return <><div className="payroll-employee-heading"><div className="payroll-person"><span className="profile-avatar payroll-avatar">{employee.name.split(' ').map((part) => part[0]).join('')}</span><div><h2>{employee.name}</h2><p>{employee.employeeId} · {employee.title} · {employee.department}</p></div></div>{admin && <div className="payroll-actions"><button className="secondary-button light-button" type="button" onClick={() => setEditing((value) => !value)}>{editing ? 'Close edit mode' : 'Edit salary structure'}</button><button className="action-button" type="button" onClick={handleGenerate}>Generate payroll</button></div>}</div>{error && <p className="form-message is-error">{error}</p>}{notice && <div className="payroll-notice" role="status">{notice}</div>}<div className="salary-summary-grid"><SalarySummaryCard label="Monthly wage" value={salary.monthlyWage ?? salary.monthlySalary ?? '—'} detail="Gross monthly" /><SalarySummaryCard label="Yearly wage" value={salary.yearlyWage ?? salary.annualSalary ?? '—'} detail="Annual gross" /><SalarySummaryCard label="Net salary" value={salary.netSalary ?? '—'} detail="After deductions" /></div>{editing && <div className="payroll-edit-panel"><strong>Salary management</strong><span>API-backed editing is enabled for HR administrators.</span><button type="button" onClick={saveSalary}>Save salary structure</button></div>}<div className="salary-columns"><SalaryComponentTable title="Salary components" rows={components} /><SalaryComponentTable title="Deductions" rows={deductions} /></div><section className="dashboard-card payroll-history"><div className="card-heading"><h2>Payroll history</h2><span className="card-link">{history.length} records</span></div><PayrollHistoryTable records={history} /></section></>
}
export default function Payroll() {
  const { user } = useAuth(); const admin = user.role === 'HR_ADMIN'; const [employees, setEmployees] = useState([]); const [selectedId, setSelectedId] = useState(user.employeeId || user.employeeCode || user.id); const [error, setError] = useState('')
  useEffect(() => { if (admin) getEmployees().then(setEmployees).catch((loadError) => setError(loadError.message)) }, [admin])
  const employee = admin ? employees.find((item) => item.id === selectedId || item.employeeId === selectedId) : { id: user.employeeId || user.employeeCode || user.id, employeeId: user.employeeId || user.employeeCode || user.id, name: user.name, title: user.jobPosition || '', department: user.department || '' }
  return <main className="dashboard-content payroll-page"><Heading label={admin ? 'HR administration' : 'Employee workspace'} copy={admin ? 'Review salary structures and payroll records across your team.' : 'Review your salary information and previous payroll records.'}>{admin ? 'Payroll' : 'My Payroll'}</Heading>{admin && <div className="payroll-selector"><label htmlFor="payroll-employee">Select employee<select id="payroll-employee" value={selectedId || ''} onChange={(event) => setSelectedId(event.target.value)}><option value="">Select employee</option>{employees.map((item) => <option key={item.id} value={item.id}>{item.name} · {item.employeeId}</option>)}</select></label></div>}{error && <p className="form-message is-error">{error}</p>}<SalaryView employee={employee} admin={admin} /></main>
}
