import { useEffect, useState } from 'react'
import InfoRow from '../components/InfoRow'
import ProfileSection from '../components/ProfileSection'
import { useAuth } from '../hooks/useAuth'
import { getProfile, updateProfile } from '../services/employeeService'

export default function Profile() {
  const { user } = useAuth(); const [profile, setProfile] = useState(null); const [form, setForm] = useState({ mobile: '', address: '', profilePicture: '' }); const [message, setMessage] = useState(''); const [error, setError] = useState('')
  useEffect(() => { getProfile().then((loaded) => { setProfile(loaded); setForm({ mobile: loaded.mobile || loaded.phone || '', address: loaded.address || '', profilePicture: loaded.profilePicture || '' }) }).catch((loadError) => setError(loadError.message)) }, [])
  async function save(event) { event.preventDefault(); try { const updated = await updateProfile({ phone: form.mobile, privateInfo: { address: form.address }, profilePicture: form.profilePicture }); setProfile((current) => ({ ...current, ...updated })); setMessage('Profile updated successfully.'); setError('') } catch (saveError) { setError(saveError.message) } }
  if (!profile) return <main className="dashboard-content"><p className="empty-state">{error || 'Loading profile...'}</p></main>
  return <main className="dashboard-content profile-page"><div className="page-heading"><div><p className="eyebrow">Personal workspace</p><h1>My Profile</h1><p className="welcome-copy">View your information and update the contact details you control.</p></div></div>{error && <p className="form-message is-error">{error}</p>}{message && <p className="payroll-notice" role="status">{message}</p>}<ProfileSection title="Work information"><InfoRow label="Employee code" value={profile.employeeId} /><InfoRow label="Department" value={profile.department} /><InfoRow label="Job position" value={profile.title} /><InfoRow label="Joining date" value={profile.joiningDate} /></ProfileSection><section className="dashboard-card profile-edit-card"><div className="card-heading"><h2>Contact details</h2><span className="card-link">Editable</span></div><form onSubmit={save}><label>Phone<input value={form.mobile} onChange={(event) => setForm({ ...form, mobile: event.target.value })} /></label><label>Address<textarea rows="3" value={form.address} onChange={(event) => setForm({ ...form, address: event.target.value })} /></label><label>Profile picture URL<input value={form.profilePicture} onChange={(event) => setForm({ ...form, profilePicture: event.target.value })} /></label><button className="action-button" type="submit">Save contact details</button></form></section><ProfileSection title="Read-only employment details"><InfoRow label="Salary" value="Managed through Payroll" /><InfoRow label="Status" value={profile.status} /><InfoRow label="Signed in as" value={user.email || profile.email} /></ProfileSection></main>
}
